name: build and deploy on main branch

on:
  push:
    branches:
      - main
      
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: |
          docker build . --tag ghcr.io/marfacabinets-tech/api:latest
      
      - name: Docker push
        run: |
          docker push ghcr.io/marfacabinets-tech/api:latest
          
      - name: Deploy to swarm
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker stack deploy --with-registry-auth -c  api-stack.yml mct
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
