name: build and deploy on main branch

on:
  push:
    branches:
      - main
      - dev
      
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: |
          docker build . --tag ghcr.io/newcourses/frontend-main:latest
      
      - name: Docker push
        run: |
          docker push ghcr.io/newcourses/frontend-main:latest

      - name: Deploy to docker compose
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker compose pull frontend-main && docker compose up --force-recreate -d frontend-main
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
